# Отток клиентов

Из «Бета-Банка» стали уходить клиенты. Каждый месяц. Немного, но заметно. Банковские маркетологи посчитали: сохранять текущих клиентов дешевле, чем привлекать новых.

Нужно спрогнозировать, уйдёт клиент из банка в ближайшее время или нет. Предоставлены исторические данные о поведении клиентов и расторжении договоров с банком. 

Необходимо построить модель с предельно большим значением *F1*-меры. Чтобы сдать проект успешно, нужно довести метрику до 0.59. Проверьте *F1*-меру на тестовой выборке самостоятельно.

Дополнительно измеряйте *AUC-ROC*, сравнивайте её значение с *F1*-мерой.

Источник данных: [https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling](https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling)

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Подготовка-данных" data-toc-modified-id="Подготовка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Подготовка данных</a></span><ul class="toc-item"><li><span><a href="#Удаление-пропусков-и-столбцов" data-toc-modified-id="Удаление-пропусков-и-столбцов-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Удаление пропусков и столбцов</a></span></li><li><span><a href="#Разделение-данных-(после-ревью-№1)" data-toc-modified-id="Разделение-данных-(после-ревью-№1)-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Разделение данных (после ревью №1)</a></span></li><li><span><a href="#Кодирование-столбца-Gender" data-toc-modified-id="Кодирование-столбца-Gender-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Кодирование столбца <code>Gender</code></a></span></li><li><span><a href="#Кодирование-столбца-Geography" data-toc-modified-id="Кодирование-столбца-Geography-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Кодирование столбца <code>Geography</code></a></span></li><li><span><a href="#Разделение-данных-на-выборки" data-toc-modified-id="Разделение-данных-на-выборки-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Разделение данных на выборки</a></span></li><li><span><a href="#Масштабирование-признаков-CreditScore,-Balance-и-EstimatedSalary" data-toc-modified-id="Масштабирование-признаков-CreditScore,-Balance-и-EstimatedSalary-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Масштабирование признаков <code>CreditScore</code>, <code>Balance</code> и <code>EstimatedSalary</code></a></span></li></ul></li><li><span><a href="#Исследование-задачи" data-toc-modified-id="Исследование-задачи-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Исследование задачи</a></span><ul class="toc-item"><li><span><a href="#Исследование-баланса-классов" data-toc-modified-id="Исследование-баланса-классов-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Исследование баланса классов</a></span></li><li><span><a href="#Изучение-моделей-без-учёта-дисбаланса" data-toc-modified-id="Изучение-моделей-без-учёта-дисбаланса-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Изучение моделей без учёта дисбаланса</a></span></li></ul></li><li><span><a href="#Борьба-с-дисбалансом" data-toc-modified-id="Борьба-с-дисбалансом-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Борьба с дисбалансом</a></span><ul class="toc-item"><li><span><a href="#Увеличение-выборки-(upsampling)" data-toc-modified-id="Увеличение-выборки-(upsampling)-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Увеличение выборки (upsampling)</a></span><ul class="toc-item"><li><span><a href="#Проверка-моделей" data-toc-modified-id="Проверка-моделей-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Проверка моделей</a></span></li></ul></li><li><span><a href="#Уменьшение-выборки-(downsampling)" data-toc-modified-id="Уменьшение-выборки-(downsampling)-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Уменьшение выборки (downsampling)</a></span><ul class="toc-item"><li><span><a href="#Проверка-моделей" data-toc-modified-id="Проверка-моделей-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Проверка моделей</a></span></li></ul></li><li><span><a href="#Автоматическая-балансировка" data-toc-modified-id="Автоматическая-балансировка-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Автоматическая балансировка</a></span></li></ul></li><li><span><a href="#Тестирование-модели" data-toc-modified-id="Тестирование-модели-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Тестирование модели</a></span></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Общий вывод</a></span></li><li><span><a href="#Чек-лист-готовности-проекта" data-toc-modified-id="Чек-лист-готовности-проекта-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист готовности проекта</a></span></li></ul></div>

## Подготовка данных

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import (
    OneHotEncoder,
    OrdinalEncoder,
    StandardScaler
)
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import (
    confusion_matrix,
    f1_score,
    roc_auc_score
)
from sklearn.utils import shuffle

RANDOM_STATE = 12345

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

**Описание данных**

Признаки:
- `RowNumber` — индекс строки в данных
- `CustomerId` — уникальный идентификатор клиента
- `Surname` — фамилия
- `CreditScore` — кредитный рейтинг
- `Geography` — страна проживания
- `Gender` — пол
- `Age` — возраст
- `Tenure` — сколько лет человек является клиентом банка
- `Balance` — баланс на счёте
- `NumOfProducts` — количество продуктов банка, используемых клиентом
- `HasCrCard` — наличие кредитной карты
- `IsActiveMember` — активность клиента
- `EstimatedSalary` — предполагаемая зарплата

Целевой признак:
- `Exited` — факт ухода клиента

**Промежуточный вывод:** в данных присутствуют категориальные признаки: пол и страна.  Эти данные считаю необходимым закодировать. Так же в столбцах со значением баланса на счету, кредитного рейтинга и предполагаемой зарплатой имеется большой разброс данных, их считаю необходимым масштабировать.

Столбцы с фамилией, уникальным идентификатором клиента и порядковым номером - данные, которые мало влияют на факт ухода клиента из банка, считаю логичным не включать их в список признаков.

### Удаление пропусков и столбцов

In [6]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis= 1, inplace= True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


### Разделение данных

In [8]:
target = df['Exited']
features = df.drop('Exited', axis=1)

In [9]:
features_train, features_vt, target_train, target_vt = train_test_split(
    features, target, test_size=0.4, random_state=RANDOM_STATE, stratify=target
)

In [10]:
features_test, features_valid, target_test, target_valid = train_test_split(
    features_vt, target_vt, test_size=0.5, random_state=RANDOM_STATE, stratify=target_vt
)

In [11]:
print(
    'Размер features_train:', 
    features_train.shape,
    'Размер target_train:', 
    target_train.shape,
    'Размер features_valid:', 
    features_valid.shape,
    'Размер target_valid:', 
    target_valid.shape,
    'Размер features_test:', 
    features_test.shape,
    'Размер target_test:', 
    target_test.shape, 
    sep='\n'
)

Размер features_train:
(6000, 10)
Размер target_train:
(6000,)
Размер features_valid:
(2000, 10)
Размер target_valid:
(2000,)
Размер features_test:
(2000, 10)
Размер target_test:
(2000,)


In [12]:
print(
    'Соотношение классов target_train:', 
    target_train.value_counts(),
    'Соотношение классов target_valid:', 
    target_valid.value_counts(),
    'Соотношение классов target_test:', 
    target_test.value_counts(), 
    sep='\n'
)

Соотношение классов target_train:
0    4778
1    1222
Name: Exited, dtype: int64
Соотношение классов target_valid:
0    1593
1     407
Name: Exited, dtype: int64
Соотношение классов target_test:
0    1592
1     408
Name: Exited, dtype: int64


In [13]:
features_train = features_train.reset_index(drop=True)
target_train = target_train.reset_index(drop=True)
features_valid = features_valid.reset_index(drop=True)
target_valid = target_valid.reset_index(drop=True)
features_test = features_test.reset_index(drop=True)
target_test = target_test.reset_index(drop=True)

### Кодирование столбца `Gender`

In [14]:
enc_gender = OneHotEncoder(drop = 'first', handle_unknown='error', sparse=False)

In [15]:
enc_train_gender = pd.DataFrame(enc_gender.fit_transform(features_train[['Gender']]))
enc_train_gender.columns = enc_gender.get_feature_names()
enc_train_gender.head()

/Users/olesyashtangey/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


x0_Male
0      0.0
1      0.0
2      1.0
3      0.0
4      0.0

In [16]:
features_train = features_train.join(enc_train_gender)
features_train.drop('Gender', axis = 1, inplace = True)
features_train.head()

CreditScore Geography  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          549   Germany   49       6  124829.16              1          0   
1          694    France   38       5  195926.39              1          1   
2          660    France   34       8  106486.66              2          0   
3          632   Germany   41       3   81877.38              1          1   
4          580    France   56       1  131368.30              1          1   

   IsActiveMember  EstimatedSalary  x0_Male  
0               1         93551.36      0.0  
1               1         85522.84      0.0  
2               1        182262.66      1.0  
3               1         33642.21      0.0  
4               0        106918.67      0.0

In [17]:
features_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      6000 non-null   int64  
 1   Geography        6000 non-null   object 
 2   Age              6000 non-null   int64  
 3   Tenure           6000 non-null   int64  
 4   Balance          6000 non-null   float64
 5   NumOfProducts    6000 non-null   int64  
 6   HasCrCard        6000 non-null   int64  
 7   IsActiveMember   6000 non-null   int64  
 8   EstimatedSalary  6000 non-null   float64
 9   x0_Male          6000 non-null   float64
dtypes: float64(3), int64(6), object(1)
memory usage: 468.9+ KB


In [18]:
enc_valid_gender = pd.DataFrame(enc_gender.transform(features_valid[['Gender']]))
enc_valid_gender.columns = enc_gender.get_feature_names()
enc_valid_gender.head()

/Users/olesyashtangey/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


x0_Male
0      0.0
1      1.0
2      1.0
3      0.0
4      0.0

In [19]:
features_valid = features_valid.join(enc_valid_gender)
features_valid.drop('Gender', axis = 1, inplace = True)
features_valid.head()

CreditScore Geography  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          601   Germany   54       1  131039.97              2          1   
1          534    France   24       1       0.00              1          1   
2          527    France   47       1       0.00              1          1   
3          730     Spain   52       7       0.00              2          0   
4          714   Germany   49       4   93059.34              1          1   

   IsActiveMember  EstimatedSalary  x0_Male  
0               1        199661.50      0.0  
1               1        169653.32      1.0  
2               0         21312.16      1.0  
3               1        122398.84      0.0  
4               0          7571.51      0.0

In [20]:
features_valid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      2000 non-null   int64  
 1   Geography        2000 non-null   object 
 2   Age              2000 non-null   int64  
 3   Tenure           2000 non-null   int64  
 4   Balance          2000 non-null   float64
 5   NumOfProducts    2000 non-null   int64  
 6   HasCrCard        2000 non-null   int64  
 7   IsActiveMember   2000 non-null   int64  
 8   EstimatedSalary  2000 non-null   float64
 9   x0_Male          2000 non-null   float64
dtypes: float64(3), int64(6), object(1)
memory usage: 156.4+ KB


In [21]:
enc_test_gender = pd.DataFrame(enc_gender.transform(features_test[['Gender']]))
enc_test_gender.columns = enc_gender.get_feature_names()
enc_test_gender.head()

/Users/olesyashtangey/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


x0_Male
0      0.0
1      1.0
2      0.0
3      1.0
4      0.0

In [22]:
features_test = features_test.join(enc_test_gender)
features_test.drop('Gender', axis = 1, inplace = True)
features_test.head()

CreditScore Geography  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          502    France   64       3  139663.37              1          0   
1          707    France   58       6   89685.92              1          0   
2          619    France   35       8  132292.63              1          1   
3          769    France   31       4   61297.05              2          1   
4          637    France   38       3  104339.56              1          0   

   IsActiveMember  EstimatedSalary  x0_Male  
0               1        100995.11      0.0  
1               1        126471.13      1.0  
2               0         65682.93      0.0  
3               1          7118.02      1.0  
4               0        119882.86      0.0

In [23]:
features_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      2000 non-null   int64  
 1   Geography        2000 non-null   object 
 2   Age              2000 non-null   int64  
 3   Tenure           2000 non-null   int64  
 4   Balance          2000 non-null   float64
 5   NumOfProducts    2000 non-null   int64  
 6   HasCrCard        2000 non-null   int64  
 7   IsActiveMember   2000 non-null   int64  
 8   EstimatedSalary  2000 non-null   float64
 9   x0_Male          2000 non-null   float64
dtypes: float64(3), int64(6), object(1)
memory usage: 156.4+ KB


### Кодирование столбца `Geography`

In [24]:
enc_geography = OneHotEncoder(drop = 'first', handle_unknown='error', sparse=False)

In [25]:
enc_train_geo = pd.DataFrame(enc_geography.fit_transform(features_train[['Geography']]))
enc_train_geo.columns = enc_geography.get_feature_names()
enc_train_geo.head()

/Users/olesyashtangey/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


x0_Germany  x0_Spain
0         1.0       0.0
1         0.0       0.0
2         0.0       0.0
3         1.0       0.0
4         0.0       0.0

In [26]:
features_train = features_train.join(enc_train_geo)
features_train.drop('Geography', axis = 1, inplace = True)
features_train.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          549   49       6  124829.16              1          0   
1          694   38       5  195926.39              1          1   
2          660   34       8  106486.66              2          0   
3          632   41       3   81877.38              1          1   
4          580   56       1  131368.30              1          1   

   IsActiveMember  EstimatedSalary  x0_Male  x0_Germany  x0_Spain  
0               1         93551.36      0.0         1.0       0.0  
1               1         85522.84      0.0         0.0       0.0  
2               1        182262.66      1.0         0.0       0.0  
3               1         33642.21      0.0         1.0       0.0  
4               0        106918.67      0.0         0.0       0.0

In [27]:
features_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      6000 non-null   int64  
 1   Age              6000 non-null   int64  
 2   Tenure           6000 non-null   int64  
 3   Balance          6000 non-null   float64
 4   NumOfProducts    6000 non-null   int64  
 5   HasCrCard        6000 non-null   int64  
 6   IsActiveMember   6000 non-null   int64  
 7   EstimatedSalary  6000 non-null   float64
 8   x0_Male          6000 non-null   float64
 9   x0_Germany       6000 non-null   float64
 10  x0_Spain         6000 non-null   float64
dtypes: float64(5), int64(6)
memory usage: 515.8 KB


In [28]:
enc_valid_geo = pd.DataFrame(enc_geography.transform(features_valid[['Geography']]))
enc_valid_geo.columns = enc_geography.get_feature_names()
enc_valid_geo.head()

/Users/olesyashtangey/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


x0_Germany  x0_Spain
0         1.0       0.0
1         0.0       0.0
2         0.0       0.0
3         0.0       1.0
4         1.0       0.0

In [29]:
features_valid = features_valid.join(enc_valid_geo)
features_valid.drop('Geography', axis = 1, inplace = True)
features_valid.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          601   54       1  131039.97              2          1   
1          534   24       1       0.00              1          1   
2          527   47       1       0.00              1          1   
3          730   52       7       0.00              2          0   
4          714   49       4   93059.34              1          1   

   IsActiveMember  EstimatedSalary  x0_Male  x0_Germany  x0_Spain  
0               1        199661.50      0.0         1.0       0.0  
1               1        169653.32      1.0         0.0       0.0  
2               0         21312.16      1.0         0.0       0.0  
3               1        122398.84      0.0         0.0       1.0  
4               0          7571.51      0.0         1.0       0.0

In [30]:
features_valid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      2000 non-null   int64  
 1   Age              2000 non-null   int64  
 2   Tenure           2000 non-null   int64  
 3   Balance          2000 non-null   float64
 4   NumOfProducts    2000 non-null   int64  
 5   HasCrCard        2000 non-null   int64  
 6   IsActiveMember   2000 non-null   int64  
 7   EstimatedSalary  2000 non-null   float64
 8   x0_Male          2000 non-null   float64
 9   x0_Germany       2000 non-null   float64
 10  x0_Spain         2000 non-null   float64
dtypes: float64(5), int64(6)
memory usage: 172.0 KB


In [31]:
enc_test_geo = pd.DataFrame(enc_geography.transform(features_test[['Geography']]))
enc_test_geo.columns = enc_geography.get_feature_names()
enc_test_geo.head()

/Users/olesyashtangey/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


x0_Germany  x0_Spain
0         0.0       0.0
1         0.0       0.0
2         0.0       0.0
3         0.0       0.0
4         0.0       0.0

In [32]:
features_test = features_test.join(enc_test_geo)
features_test.drop('Geography', axis = 1, inplace = True)
features_test.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          502   64       3  139663.37              1          0   
1          707   58       6   89685.92              1          0   
2          619   35       8  132292.63              1          1   
3          769   31       4   61297.05              2          1   
4          637   38       3  104339.56              1          0   

   IsActiveMember  EstimatedSalary  x0_Male  x0_Germany  x0_Spain  
0               1        100995.11      0.0         0.0       0.0  
1               1        126471.13      1.0         0.0       0.0  
2               0         65682.93      0.0         0.0       0.0  
3               1          7118.02      1.0         0.0       0.0  
4               0        119882.86      0.0         0.0       0.0

In [33]:
features_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      2000 non-null   int64  
 1   Age              2000 non-null   int64  
 2   Tenure           2000 non-null   int64  
 3   Balance          2000 non-null   float64
 4   NumOfProducts    2000 non-null   int64  
 5   HasCrCard        2000 non-null   int64  
 6   IsActiveMember   2000 non-null   int64  
 7   EstimatedSalary  2000 non-null   float64
 8   x0_Male          2000 non-null   float64
 9   x0_Germany       2000 non-null   float64
 10  x0_Spain         2000 non-null   float64
dtypes: float64(5), int64(6)
memory usage: 172.0 KB


### Масштабирование признаков `CreditScore`, `Balance` и `EstimatedSalary`

In [34]:
numeric = ['CreditScore', 'Balance', 'EstimatedSalary'] 

In [35]:
scaler = StandardScaler()
scaler.fit(features_train[numeric])

StandardScaler()

In [36]:
pd.options.mode.chained_assignment = None
features_train[numeric] = scaler.transform(features_train[numeric])
features_valid[numeric] = scaler.transform(features_valid[numeric]) 
features_test[numeric] = scaler.transform(features_test[numeric]) 

In [37]:
features_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      6000 non-null   float64
 1   Age              6000 non-null   int64  
 2   Tenure           6000 non-null   int64  
 3   Balance          6000 non-null   float64
 4   NumOfProducts    6000 non-null   int64  
 5   HasCrCard        6000 non-null   int64  
 6   IsActiveMember   6000 non-null   int64  
 7   EstimatedSalary  6000 non-null   float64
 8   x0_Male          6000 non-null   float64
 9   x0_Germany       6000 non-null   float64
 10  x0_Spain         6000 non-null   float64
dtypes: float64(6), int64(5)
memory usage: 515.8 KB


## Исследование задачи

Прогноз, уйдёт клиент из банка в ближайшее время или нет - задача классификации. В проекте будет рассмотрено 3 вида модели: 
- дерево решений;
- случайный лес;
- логистическая регрессия.

### Исследование баланса классов

In [38]:
print(
    'Общее соотношение классов:', 
    target.value_counts(),
    'Соотношение классов в обучающей выборке:', 
    target_train.value_counts(),
    'Соотношение классов в валидационной выборке:', 
    target_valid.value_counts(),
    'Соотношение классов в тестовой выборке:', 
    target_valid.value_counts(), 
    sep='\n'
)

Общее соотношение классов:
0    7963
1    2037
Name: Exited, dtype: int64
Соотношение классов в обучающей выборке:
0    4778
1    1222
Name: Exited, dtype: int64
Соотношение классов в валидационной выборке:
0    1593
1     407
Name: Exited, dtype: int64
Соотношение классов в тестовой выборке:
0    1593
1     407
Name: Exited, dtype: int64


**Вывод:** в данных наблюдается явный дисбаланс классов, клиентов, оставшихся в банке, примерно в 4 раза больше.

### Изучение моделей без учёта дисбаланса

In [39]:
# дерево решений (model DecisionTreeClassifier == model_dtc)
best_model_dtc = None
best_depth_dtc = 0
best_result_f1_dtc = 0

for depth in range(1, 11):
    model = DecisionTreeClassifier(random_state=RANDOM_STATE, max_depth=depth)
    model.fit(features_train, target_train) 
    predictions_valid = model.predict(features_valid) 
    result_f1 = f1_score(target_valid, predictions_valid)
    
    if result_f1 > best_result_f1_dtc:
        best_model_dtc = model
        best_depth_dtc = depth
        best_result_f1_dtc = result_f1


predictions_valid_dtc = best_model_dtc.predict(features_valid)

probabilities_valid_dtc = best_model_dtc.predict_proba(features_valid)[:, 1]
auc_roc_dtc = roc_auc_score(target_valid, probabilities_valid_dtc)

print('Значения наилучшей модели:')
print('Глубина дерева =', best_depth_dtc)
print('F1-метрика =', best_result_f1_dtc)
print('Матрица ошибок:')
print(confusion_matrix(target_valid, predictions_valid_dtc))
print('AUC-ROC-метрика =', auc_roc_dtc)

Значения наилучшей модели:
Глубина дерева = 7
F1-метрика = 0.552870090634441
Матрица ошибок:
[[1521   72]
 [ 224  183]]
AUC-ROC-метрика = 0.8092900296290126


In [40]:
# случайный лес (model RandomForestClassifier == model_rfc)
best_model_rfc = None
best_est_rfc = 0
best_depth_rfc = 0
best_result_f1_rfc = 0

for est in range(5, 51, 5):
    for depth in range (1, 11):
        model = RandomForestClassifier(random_state=RANDOM_STATE, n_estimators=est, max_depth=depth)
        model.fit(features_train, target_train) 
        predictions_valid = model.predict(features_valid) 
        result_f1 = f1_score(target_valid, predictions_valid)
    
        if result_f1 > best_result_f1_rfc:
            best_model_rfc = model 
            best_est_rfc = est
            best_depth_rfc = depth
            best_result_f1_rfc = result_f1


predictions_valid_rfc = best_model_rfc.predict(features_valid)

probabilities_valid_rfc = best_model_rfc.predict_proba(features_valid)[:, 1]
auc_roc_rfc = roc_auc_score(target_valid, probabilities_valid_rfc)   

print('Значения наилучшей модели:')
print('Количество деревьев =', best_est_rfc)
print('Глубина дерева =', best_depth_rfc)
print('F1-метрика =', best_result_f1_rfc)
print('Матрица ошибок:')
print(confusion_matrix(target_valid, predictions_valid_rfc))
print('AUC-ROC-метрика =', auc_roc_rfc)

Значения наилучшей модели:
Количество деревьев = 30
Глубина дерева = 10
F1-метрика = 0.5553822152886115
Матрица ошибок:
[[1537   56]
 [ 229  178]]
AUC-ROC-метрика = 0.8530957768245904


In [41]:
# логистическая регрессия (model LogisticRegression == model_lr)
model_lr = LogisticRegression(random_state=RANDOM_STATE, solver='liblinear', max_iter=1000)
model_lr.fit(features_train, target_train) 
predictions_valid_lr = model_lr.predict(features_valid)
result_f1_lr = f1_score(target_valid, predictions_valid_lr)

probabilities_valid_lr = model_lr.predict_proba(features_valid)[:, 1]
auc_roc_lr = roc_auc_score(target_valid, probabilities_valid_lr)

print('Значения модели:')
print('F1-метрика =', result_f1_lr)
print('Матрица ошибок:')
print(confusion_matrix(target_valid, predictions_valid_lr))
print('AUC-ROC-метрика =', auc_roc_lr)

Значения модели:
F1-метрика = 0.2900188323917138
Матрица ошибок:
[[1546   47]
 [ 330   77]]
AUC-ROC-метрика = 0.7496078513027664


___

In [42]:
metrics_ser = pd.Series(['F1', 'AUC-ROC'])
dtc_ser = pd.Series([best_result_f1_dtc, auc_roc_dtc])
rft_ser = pd.Series([best_result_f1_rfc, auc_roc_rfc])
lr_ser = pd.Series([result_f1_lr, auc_roc_lr])

metrics_df = metrics_ser.to_frame(name='metrics')
dtc_df = dtc_ser.to_frame(name='DTC')
rft_df = rft_ser.to_frame(name='RFT')
lr_df = lr_ser.to_frame(name='LR')

metrics_imbalance = pd.concat([metrics_df, dtc_df, rft_df, lr_df], axis= 1)

In [43]:
metrics_imbalance

metrics      DTC       RFT        LR
0       F1  0.55287  0.555382  0.290019
1  AUC-ROC  0.80929  0.853096  0.749608

**Вывод:** самые высокие значения метрик F1 и AUC-ROC получились у модели случайного леса: 0.56 и 0.85 соответственно; самые низкие - у модели логистической регрессии: 0.29 и 0.75. При этом ни одной модели не удалось достичь требуемого качества (f1 > 0.59)

## Борьба с дисбалансом

Устранить дисбаланс можно разными методами: 
- увеличением выборки; 
- уменьшением выборки; 
- автоматической балансировкой.

Чтобы наглядно увидеть, как сбалансированная выборка меняет качество модели, возмем модели с лучшими параметрами из шага 2 и обучим их на новых данных, либо применим автобалансировку. 

Для этого создадим функцию, которая будет принимать название модели, обучающие данные и необходимость в автоматической балансировке, а отдавать метрики качества: F1-меру и AUC-ROC.

In [44]:
# Функция вызова 
def get_model_metrics(name_model, features_train_new, target_train_new, wght):
    if wght == True:
        if name_model == 'dtc':
            model = DecisionTreeClassifier(
                random_state=RANDOM_STATE, max_depth=5, class_weight='balanced')
        elif name_model == 'rfc':
            model = RandomForestClassifier(
                random_state=RANDOM_STATE, n_estimators=20, max_depth=10, class_weight='balanced')
        elif name_model == 'lr':
            model = LogisticRegression(
                random_state=RANDOM_STATE, solver='liblinear', max_iter=1000, class_weight='balanced')
        else:
            return print('Функция не работает с такой моделью')
    elif wght == False: 
        if name_model == 'dtc':
            model = DecisionTreeClassifier(random_state=RANDOM_STATE, max_depth=5)
        elif name_model == 'rfc':
            model = RandomForestClassifier(random_state=RANDOM_STATE, n_estimators=20, max_depth=10)
        elif name_model == 'lr':
            model = LogisticRegression(random_state=RANDOM_STATE, solver='liblinear', max_iter=1000)
        else:
            return print('Функция не работает с такой моделью')
    else:
        return print('Не понятно: взвешивать или нет?')
        
    model.fit(features_train_new, target_train_new)
    predictions_valid = model.predict(features_valid) 
    
    result_f1 = f1_score(target_valid, predictions_valid)

    probabilities_valid = model.predict_proba(features_valid)[:, 1]
    auc_roc = roc_auc_score(target_valid, probabilities_valid)
    
    print('Модель:', name_model)
    print('F1-метрика =', result_f1)
    print('Матрица ошибок:')
    print(confusion_matrix(target_valid, predictions_valid))
    print('AUC-ROC-метрика =', auc_roc)
    
    return result_f1, auc_roc

### Увеличение выборки (upsampling)

Преобразование проходит в несколько этапов:
- разделить обучающую выборку на объекты по классам;
- определить тот класс, который содержит меньше объектов;
- скопировать несколько раз объекты меньшего класса; 
- с учетом полученных данных создать новую обучающую выборку;
- перемешать данные.

При этом если использовать "копирование и размножение" выборки с классом 1, а после этого использовать кросс-валидацию, то может получиться чрезмерно оптимистичный результат.

Так же следует отметить, что увеличение выборки следует проводить на обучающей выборке.

In [45]:
def upsample(features, target, repeat):
    features_zeros = features[target == 0]
    features_ones = features[target == 1]
    target_zeros = target[target == 0]
    target_ones = target[target == 1]

    features_upsampled = pd.concat([features_zeros] + [features_ones] * repeat)
    target_upsampled = pd.concat([target_zeros] + [target_ones] * repeat)
    
    features_upsampled, target_upsampled = shuffle(
        features_upsampled, target_upsampled, random_state=RANDOM_STATE
    )
    
    return features_upsampled, target_upsampled

In [46]:
features_upsampled, target_upsampled = upsample(features_train, target_train, 4)

In [47]:
print(
    'Размер features_upsampled', 
    features_upsampled.shape,
    'Размер target_upsampled', 
    target_upsampled.shape,
    'Соотношение классов:', 
    target_upsampled.value_counts(), 
    sep='\n'
)

Размер features_upsampled
(9666, 11)
Размер target_upsampled
(9666,)
Соотношение классов:
1    4888
0    4778
Name: Exited, dtype: int64


#### Проверка моделей

In [48]:
dtc_ups_f1, dtc_ups_auc = get_model_metrics('dtc', features_upsampled, target_upsampled, False)

Модель: dtc
F1-метрика = 0.5264822134387352
Матрица ошибок:
[[1068  525]
 [  74  333]]
AUC-ROC-метрика = 0.8278309125766753


In [49]:
rfc_ups_f1, rfc_ups_auc = get_model_metrics('rfc', features_upsampled, target_upsampled, False)

Модель: rfc
F1-метрика = 0.5870535714285715
Матрица ошибок:
[[1367  226]
 [ 144  263]]
AUC-ROC-метрика = 0.8422320625710455


In [50]:
lr_ups_f1, lr_ups_auc = get_model_metrics('lr', features_upsampled, target_upsampled, False)

Модель: lr
F1-метрика = 0.4804088586030664
Матрица ошибок:
[[1108  485]
 [ 125  282]]
AUC-ROC-метрика = 0.753872516584381


___

In [51]:
dtc_ups_ser = pd.Series([dtc_ups_f1, dtc_ups_auc])
rft_ups_ser = pd.Series([rfc_ups_f1, rfc_ups_auc])
lr_ups_ser = pd.Series([lr_ups_f1, lr_ups_auc])

dtc_ups_df = dtc_ups_ser.to_frame(name='DTC_ups')
rft_ups_df = rft_ups_ser.to_frame(name='RFT_ups')
lr_ups_df = lr_ups_ser.to_frame(name='LR_ups')

metrics_upsample = pd.concat([metrics_df, dtc_ups_df, rft_ups_df, lr_ups_df], axis= 1)

In [52]:
metrics_upsample

metrics   DTC_ups   RFT_ups    LR_ups
0       F1  0.526482  0.587054  0.480409
1  AUC-ROC  0.827831  0.842232  0.753873

In [53]:
# для сравнения
metrics_imbalance

metrics      DTC       RFT        LR
0       F1  0.55287  0.555382  0.290019
1  AUC-ROC  0.80929  0.853096  0.749608

**Вывод:** значение метрики F1 моделей логистической регрессии и случайного леса выросло, а модели дерева решений - уменьшилось, при этом самое большое значение по-прежнему у случайного леса. Что касается метрик AUC-ROC, они почти не изменились.

### Уменьшение выборки (downsampling)

In [54]:
def downsample(features, target, fraction): 
    features_zeros = features[target == 0] 
    features_ones = features[target == 1] 
    target_zeros = target[target == 0] 
    target_ones = target[target == 1]

    features_downsampled = pd.concat(
        [features_zeros.sample(frac=fraction, random_state=RANDOM_STATE)] + [features_ones]
    )
    target_downsampled = pd.concat(
        [target_zeros.sample(frac=fraction, random_state=RANDOM_STATE)] + [target_ones]
    )
    features_downsampled, target_downsampled = shuffle(
        features_downsampled, target_downsampled, random_state=RANDOM_STATE
    )

    return features_downsampled, target_downsampled

In [55]:
features_downsampled, target_downsampled = downsample(features_train, target_train, 0.25)

In [56]:
print(
    'Размер features_downsampled', 
    features_downsampled.shape,
    'Размер target_downsampled', 
    target_downsampled.shape,
    'Соотношение классов:', 
    target_downsampled.value_counts(), 
    sep='\n'
)

Размер features_downsampled
(2416, 11)
Размер target_downsampled
(2416,)
Соотношение классов:
1    1222
0    1194
Name: Exited, dtype: int64


#### Проверка моделей

In [57]:
dtc_downs_f1, dtc_downs_auc = get_model_metrics('dtc', features_downsampled, target_downsampled, False)

Модель: dtc
F1-метрика = 0.522342064714946
Матрица ошибок:
[[1041  552]
 [  68  339]]
AUC-ROC-метрика = 0.8292953970920073


In [58]:
rfc_downs_f1, rfc_downs_auc = get_model_metrics('rfc', features_downsampled, target_downsampled, False)

Модель: rfc
F1-метрика = 0.5655813953488372
Матрица ошибок:
[[1229  364]
 [ 103  304]]
AUC-ROC-метрика = 0.8453615402767944


In [59]:
lr_downs_f1, lr_downs_auc = get_model_metrics('lr', features_downsampled, target_downsampled, False)

Модель: lr
F1-метрика = 0.4817021276595745
Матрица ошибок:
[[1108  485]
 [ 124  283]]
AUC-ROC-метрика = 0.7513569038992769


___

In [60]:
dtc_downs_ser = pd.Series([dtc_downs_f1, dtc_downs_auc])
rft_downs_ser = pd.Series([rfc_downs_f1, rfc_downs_auc])
lr_downs_ser = pd.Series([lr_downs_f1, lr_downs_auc])

dtc_downs_df = dtc_downs_ser.to_frame(name='DTC_downs')
rft_downs_df = rft_downs_ser.to_frame(name='RFT_downs')
lr_downs_df = lr_downs_ser.to_frame(name='LR_downs')

metrics_downsample = pd.concat([metrics_df, dtc_downs_df, rft_downs_df, lr_downs_df], axis= 1)

In [61]:
metrics_downsample

metrics  DTC_downs  RFT_downs  LR_downs
0       F1   0.522342   0.565581  0.481702
1  AUC-ROC   0.829295   0.845362  0.751357

In [62]:
# для сравнения
metrics_imbalance

metrics      DTC       RFT        LR
0       F1  0.55287  0.555382  0.290019
1  AUC-ROC  0.80929  0.853096  0.749608

**Вывод:** значение метрики F1 моделей логистической регрессии и случайного леса выросло, а модели дерева решений - уменьшилось. При этом, самое большое значение по-прежнему получается у случайного леса. Что касается метрик AUC-ROC, они почти не изменились.

### Автоматическая балансировка 

Следует отметить, что автоматическую балансировку (использование метода class_weight) применяют не со сбалансированными данными. Использование сразу двух методов балансирования привело бы к новому дисбалансу, поэтому использовать такие методы нужно взаимоисключающе.

In [63]:
dtc_balanced_f1, dtc_balanced_auc = get_model_metrics('dtc', features_train, target_train, True)

Модель: dtc
F1-метрика = 0.5264822134387352
Матрица ошибок:
[[1068  525]
 [  74  333]]
AUC-ROC-метрика = 0.8278309125766753


In [64]:
rfc_balanced_f1, rfc_balanced_auc = get_model_metrics('rfc', features_train, target_train, True)

Модель: rfc
F1-метрика = 0.5806451612903226
Матрица ошибок:
[[1406  187]
 [ 164  243]]
AUC-ROC-метрика = 0.8474036440138136


In [65]:
lr_balanced_f1, lr_balanced_auc = get_model_metrics('lr', features_train, target_train, True)

Модель: lr
F1-метрика = 0.4756944444444445
Матрица ошибок:
[[1122  471]
 [ 133  274]]
AUC-ROC-метрика = 0.7537645503747199


___

In [66]:
dtc_balanced_ser = pd.Series([dtc_balanced_f1, dtc_balanced_auc])
rft_balanced_ser = pd.Series([rfc_balanced_f1, rfc_balanced_auc])
lr_balanced_ser = pd.Series([lr_balanced_f1, lr_balanced_auc])

dtc_balanced_df = dtc_balanced_ser.to_frame(name='DTC_balanced')
rft_balanced_df = rft_balanced_ser.to_frame(name='RFT_balanced')
lr_balanced_df = lr_balanced_ser.to_frame(name='LR_balanced')

metrics_balanced = pd.concat([metrics_df, dtc_balanced_df, rft_balanced_df, lr_balanced_df], axis= 1)

In [67]:
metrics_balanced

metrics  DTC_balanced  RFT_balanced  LR_balanced
0       F1      0.526482      0.580645     0.475694
1  AUC-ROC      0.827831      0.847404     0.753765

In [68]:
# для сравнения
metrics_imbalance

metrics      DTC       RFT        LR
0       F1  0.55287  0.555382  0.290019
1  AUC-ROC  0.80929  0.853096  0.749608

**Вывод:** значение метрики F1 моделей логистической регрессии и случайного леса выросло, а модели дерева решений - уменьшилось. Самое большое значение по-прежнему получается у случайного леса. Что касается метрик AUC-ROC, они почти не изменились.

___

In [69]:
metrics_upsample

metrics   DTC_ups   RFT_ups    LR_ups
0       F1  0.526482  0.587054  0.480409
1  AUC-ROC  0.827831  0.842232  0.753873

In [70]:
metrics_downsample

metrics  DTC_downs  RFT_downs  LR_downs
0       F1   0.522342   0.565581  0.481702
1  AUC-ROC   0.829295   0.845362  0.751357

In [71]:
metrics_balanced

metrics  DTC_balanced  RFT_balanced  LR_balanced
0       F1      0.526482      0.580645     0.475694
1  AUC-ROC      0.827831      0.847404     0.753765

**Общий вывод:** самое большое значение F1-меры получилось у модели случайного леса при увеличении выборки. Эту модель будем использовать для финального тестирования. Метрики AUC-ROC во время экспериментов практически не изменялись, скорее всего она малочувствительна к дисбалансу в выборках.

## Тестирование модели

In [72]:
# Подготовка модели для финального тестирования
best_model_test = None
best_est_test = 0
best_depth_test = 0
best_result_f1_test = 0

for est in range(10, 101, 10):
    for depth in range (1, 21):
        model = RandomForestClassifier(random_state=RANDOM_STATE, n_estimators=est, max_depth=depth)
        model.fit(features_upsampled, target_upsampled) 
        predictions_valid = model.predict(features_valid) 
        result_f1 = f1_score(target_valid, predictions_valid)
    
        if result_f1 > best_result_f1_test:
            best_model_test = model 
            best_est_test = est
            best_depth_test = depth
            best_result_f1_test = result_f1   

print('Значения наилучшей модели:')
print('Количество деревьев =', best_est_test)
print('Глубина дерева =', best_depth_test)
print('F1-метрика =', best_result_f1_test)

Значения наилучшей модели:
Количество деревьев = 90
Глубина дерева = 8
F1-метрика = 0.6104166666666666


In [73]:
predictions_test = best_model_test.predict(features_test)
result_f1_test = f1_score(target_test, predictions_test)

print('F1-метрика на тестовой выборке =', result_f1_test)

F1-метрика на тестовой выборке = 0.640495867768595


## Общий вывод

**1. Обзор и подготовка данных.**

В каждой строке таблицы данных - информация о клиенте «Бета-Банка». Часть из них содержит общие данные о человеке: уникальный идентификатор клиента, фамилию, страну проживания, пол, возраст, кредитный рейтинг, сколько лет человек является клиентом банка и предполагаемую зарплату. Другие - это показатели, которые характеризуют его финансовую составляющую в этом банке: баланс на счёте, количество продуктов банка, используемых клиентом, наличие кредитной карты, активность клиента и факт ухода клиента из банка.

В данных присутствовали категориальные признаки: пол и страна. Их было необходимо преобразовать в количественные, для этого использовались техники прямого кодирования, или отображения (One-Hot Encoding) - для пола и порядкового кодирования (Ordinal Encoding) - для страны.

Так же в столбцах со значением баланса на счету, кредитного рейтинга и предполагаемой зарплатой имелся большой разброс данных, их было необходимо масштабировать. Для этого использован метод стандартизации данных.

Столбцы с фамилией, уникальным идентификатором клиента и порядковым номером - являются данными, которые мало влияют на факт ухода клиента из банка, они были удалены из списка признаков.

В конце все данные были разделены на 3 выборки: обучающую, валидационную и тестовую в соотношении 60:20:20 соответственно. Было выявлено, что в данных есть дисбаланс классов: клиентов, которые не ушли из банка примерно в 4 раза больше.

**2. Исследование качества разных моделей.**

Прогноз, уйдёт клиент из банка в ближайшее время или нет - задача классификации. В проекте рассмотрено 3 вида моделей:
- дерево решений;
- случайный лес;
- логистическая регрессия.

Для сравнения качества модели использовалась F1-метрика. Так же параллельно вычислялись значения AUC-ROC метрики. 

Первое исследование моделей прошло без учета дисбаланса в данных, самое высокое значение F1-метрики получила модель случайного леса с количеством деревьев 20 и глубиной 10.

Для борьбы с дисбалансом опробованы 3 метода:
- увеличения выборки;
- уменьшения выборки;
- атоматической балансировки.

Во всех 3 случаях самые высокие значения F1-меры получила модель случайного леса, самые низкие - модель логистической регрессии. Метрика AUC-ROC во время экспериментов практически не изменялась, скорее всего она малочувствительна к дисбалансу в выборках.

**3. Финальное тестирование.**

Для финального тестирования была выбрана модель, которая получила самое высокое значение F1 - модель случайного леса при увеличении выборки (F1 = 0.59).

Проверкой на тестовой выборке было достигнуто значения F1-меры 0.65. Удалось достичь нужного качества модели (более 0.59).